/**
 * Checks that the native iOS plugins the web code relies on are really part of
 * the app build. Pure functions over file contents; the CLI that reads the files
 * is scripts/verify-ios-plugins.ts (also run by ios/App/ci_scripts/ci_post_clone.sh).
 *
 * Why: Capacitor only registers the classes listed in `packageClassList` of the
 * GENERATED `capacitor.config.json` (gitignored, written by `cap sync ios`), and it
 * skips a listed class that is not linked WITHOUT any error. Without
 * `MomentsNativeAuthPlugin` the web side sees `isPluginAvailable("MomentsNativeAuth")`
 * as false and silently uses the Safari login fallback.
 */

export interface NativePlugin {
  /** Class name Capacitor loads through NSClassFromString (`@objc(...)` name). */
  readonly nativeClass: string;
  /** Name the web code registers (`registerPlugin("...")`). */
  readonly jsName: string;
  /** Product name CapApp-SPM/Package.swift must depend on. */
  readonly spmProduct: string;
  /** Plugin source whose class and jsName must match the two names above. */
  readonly sourcePath: string;
}

export const NATIVE_AUTH_PLUGIN: NativePlugin = {
  nativeClass: "MomentsNativeAuthPlugin",
  jsName: "MomentsNativeAuth",
  spmProduct: "MomentsForeverCapacitorNativeAuth",
  sourcePath: "packages/capacitor-native-auth/ios/Sources/MomentsNativeAuthPlugin/MomentsNativeAuthPlugin.swift",
};

export const PHOTO_LIBRARY_PLUGIN_CLASS = "MomentsPhotoLibraryPlugin";

export function readPackageClassList(configJson: string): string[] | null {
  try {
    const parsed = JSON.parse(configJson) as { packageClassList?: unknown };
    if (!Array.isArray(parsed.packageClassList)) return null;
    return parsed.packageClassList.filter((item): item is string => typeof item === "string");
  } catch {
    return null;
  }
}

/** `capacitor.config.json` as generated by `cap sync ios` (or found inside a built .app). */
export function checkRegisteredInConfig(configJson: string, plugin: NativePlugin = NATIVE_AUTH_PLUGIN): string[] {
  const list = readPackageClassList(configJson);
  if (list === null) {
    return ["capacitor.config.json is not valid JSON or has no packageClassList. Run `npm run cap:sync` in apps/web."];
  }
  return list.includes(plugin.nativeClass)
    ? []
    : [
        `${plugin.nativeClass} is missing from packageClassList in capacitor.config.json ` +
          `(found: ${list.join(", ") || "nothing"}). Without it the app silently falls back to the Safari login. ` +
          "Run `npm ci` and `npm run cap:sync` in apps/web.",
      ];
}

/** `CapApp-SPM/Package.swift` as generated by `cap sync ios`. */
export function checkLinkedInSpmManifest(packageSwift: string, plugin: NativePlugin = NATIVE_AUTH_PLUGIN): string[] {
  const errors: string[] = [];
  const dependency = new RegExp(`\\.package\\(name:\\s*"${plugin.spmProduct}"`);
  const product = new RegExp(`\\.product\\(name:\\s*"${plugin.spmProduct}"`);
  if (!dependency.test(packageSwift)) {
    errors.push(`CapApp-SPM/Package.swift has no .package(name: "${plugin.spmProduct}", path: …) dependency.`);
  }
  if (!product.test(packageSwift)) {
    errors.push(`CapApp-SPM/Package.swift does not link the product "${plugin.spmProduct}" into the CapApp-SPM target.`);
  }
  return errors;
}

/** The Swift source: the native class and the JS name must match what is registered. */
export function checkPluginSource(swiftSource: string, plugin: NativePlugin = NATIVE_AUTH_PLUGIN): string[] {
  const errors: string[] = [];
  if (!new RegExp(`@objc\\(${plugin.nativeClass}\\)`).test(swiftSource)) {
    errors.push(`${plugin.sourcePath} does not declare @objc(${plugin.nativeClass}).`);
  }
  if (!new RegExp(`jsName\\s*=\\s*"${plugin.jsName}"`).test(swiftSource)) {
    errors.push(`${plugin.sourcePath} does not set jsName = "${plugin.jsName}" (the name registerPlugin uses).`);
  }
  return errors;
}

/** A built executable (App.app/App): the class name is in its binary only if it was linked. */
export function checkBinaryContainsPlugin(binary: Uint8Array, plugin: NativePlugin = NATIVE_AUTH_PLUGIN): string[] {
  const found = Buffer.from(binary).includes(Buffer.from(plugin.nativeClass));
  return found
    ? []
    : [`The app executable does not contain ${plugin.nativeClass}: the plugin was not linked into this build.`];
}

export interface PluginInputs {
  readonly configJson: string;
  readonly packageSwift: string;
  readonly pluginSource: string;
}

/** Everything the repo + `cap sync` output must satisfy before an Archive. */
export function verifyNativeAuthPlugin(inputs: PluginInputs): string[] {
  return [
    ...checkRegisteredInConfig(inputs.configJson),
    ...checkLinkedInSpmManifest(inputs.packageSwift),
    ...checkPluginSource(inputs.pluginSource),
  ];
}
